apiVersion: v1
kind: Service
metadata:
  labels:
    service: locations-event-api
  name: locations-event-api
spec:
  ports:
  - name: "5002"
    port: 5002
    targetPort: 5002
    nodePort: 30003
  selector:
    service: locations-event-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: locations-event-api
  name: locations-event-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: locations-event-api
  template:
    metadata:
      labels:
        service: locations-event-api
    spec:
      containers:
      - image: chizzydavid/nd064-locations-event-api:latest
        name: locations-event-api
        imagePullPolicy: Always
        resources:
          limits:
            memory: 256Mi
            cpu: 500m
          requests:
            memory: 150Mi            
            cpu: 250m
      restartPolicy: Always
