# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import location_pb2 as location__pb2


class LocationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddLocation = channel.unary_unary(
                '/locationPackage.Location/AddLocation',
                request_serializer=location__pb2.LocationItem.SerializeToString,
                response_deserializer=location__pb2.LocationItem.FromString,
                )


class LocationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LocationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.AddLocation,
                    request_deserializer=location__pb2.LocationItem.FromString,
                    response_serializer=location__pb2.LocationItem.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'locationPackage.Location', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Location(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/locationPackage.Location/AddLocation',
            location__pb2.LocationItem.SerializeToString,
            location__pb2.LocationItem.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
